version: '3.9'

services:
   database:
      image: postgres
      restart: always
      container_name: sunny_psql
      ports:
         - '5432:5432'
      environment:
         POSTGRES_DB: sunny
         POSTGRES_PASSWORD: secret
